[system] Unified package manager check.
All systems now check the package manager and exit on failure if
requested.

diff --git a/install_system_packages_fedora b/install_system_packages_fedora
--- a/install_system_packages_fedora
+++ b/install_system_packages_fedora
@@ -51,10 +51,17 @@ if [ -z "${pm}" ]; then
 fi
 
 # update and check packages
-${pm_check}
+${pm_update}
+if ! ${pm_check} ; then
+    echo "warning: Package manager check failed, continue anyway (y/n)?: \c"
+    read -r yn
+    if [ "${yn}" != "y" ]; then
+	exit 1
+    fi
+fi
+${pm_update}
 
 # upgrade existing packages
-${pm_update}
 ${pm_upgrade}
 
 # install packages for homedir installer
