[boost] Print error messages to standard error in install script.

diff --git a/install_boost b/install_boost
--- a/install_boost
+++ b/install_boost
@@ -7,7 +7,7 @@ set -u
 set -e
 
 if [ $# -ne 1 ]; then
-    printf "usage: %s <version>\n" "$(basename "$0")"
+    printf "usage: %s <version>\n" "$(basename "$0")" 1>&2
     exit 1
 fi
 
@@ -19,17 +19,17 @@ filename="${directory}".tar.gz
 minor="$(printf "%s" "${version}" | sed 's/^[0-9]\.\([0-9][0-9]\)\.[0-9]/\1/')"
 
 if [ ! -d "${root}" ]; then
-    printf "error: %s does not exist.\n" "${root}"
+    printf "error: %s does not exist.\n" "${root}" 1>&2
     exit 1
 fi
 
 if [ -d "${root}"/"${directory}" ]; then
-    printf "error: %s already exists.\n" "${root}"/"${directory}"
+    printf "error: %s already exists.\n" "${root}"/"${directory}" 1>&2
     exit 1
 fi
 
 if [ -e "${root}"/"${filename}" ]; then
-    printf "error: %s already exists.\n" "${root}"/"${filename} "
+    printf "error: %s already exists.\n" "${root}"/"${filename} " 1>&2
     exit 1
 fi
 
@@ -38,14 +38,14 @@ url=https://boostorg.jfrog.io/artifactory/main/release/"${version}"/source/"${fi
 wget --no-clobber --output-document "${root}"/"${filename}" "${url}"
 
 if [ ! -e "${root}"/"${filename}" ]; then
-    printf "error: %s does not exist.\n" "${root}"/"${filename}"
+    printf "error: %s does not exist.\n" "${root}"/"${filename}" 1>&2
     exit 1
 fi
 
 tar xfz "${root}"/"${filename}" -C "${root}"
 
 if [ ! -d "${root}"/"${directory}" ]; then
-    printf "error: %s does not exist.\n" "${root}"/"${directory} "
+    printf "error: %s does not exist.\n" "${root}"/"${directory} " 1>&2
     exit 1
 fi
 
