[system] Print error messages to standard error in install scripts.

diff --git a/install_system_packages_debian b/install_system_packages_debian
--- a/install_system_packages_debian
+++ b/install_system_packages_debian
@@ -18,7 +18,7 @@ pm_cleanup=
 
 # check if apt is installed
 if [ -z "$(which apt 2> /dev/null)" ]; then
-    printf "warning: apt not found\n"
+    printf "warning: apt not found\n" 1>&2
 else
     pm="apt"
     pm_check="true"
@@ -30,7 +30,7 @@ fi
 
 # check if package manager is installed
 if [ -z "${pm}" ]; then
-    printf "error: Package manager not found.\n"
+    printf "error: Package manager not found.\n" 1>&2
     exit 1
 fi
 
diff --git a/install_system_packages_fedora b/install_system_packages_fedora
--- a/install_system_packages_fedora
+++ b/install_system_packages_fedora
@@ -34,7 +34,7 @@ pm_cleanup=
 
 # check if dnf is installed
 if [ -z "$(which dnf 2> /dev/null)" ]; then
-    printf "warning: dnf not found.\n"
+    printf "warning: dnf not found.\n" 1>&2
 else
     pm="dnf"
     pm_check="true"
@@ -52,7 +52,7 @@ fi
 # check if yum is installed, if package manager is not
 if [ -z "${pm}" ]; then
     if [ -z "$(which yum 2> /dev/null)" ]; then
-        printf "warning: yum not found.\n"
+        printf "warning: yum not found.\n" 1>&2
     else
         pm="yum"
         pm_check="true"
@@ -65,7 +65,7 @@ fi
 
 # check if package manager is installed
 if [ -z "${pm}" ]; then
-    printf "error: Package manager not found.\n"
+    printf "error: Package manager not found.\n" 1>&2
     exit 1
 fi
 
diff --git a/install_system_packages_macos b/install_system_packages_macos
--- a/install_system_packages_macos
+++ b/install_system_packages_macos
@@ -18,7 +18,7 @@ pm_cleanup=
 
 # check if Homebrew is installed
 if [ -z "$(which brew 2> /dev/null)" ]; then
-    printf "warning: Homewbrew (brew) not found.\n"
+    printf "warning: Homewbrew (brew) not found.\n" 1>&2
 else
     pm="brew"
     pm_check="${pm} doctor"
