[packages] Simplify interpreter package scripts.
This simplifies the logic in these scripts since now they can exit when
they cannot install.

diff --git a/install_node_packages b/install_node_packages
--- a/install_node_packages
+++ b/install_node_packages
@@ -3,15 +3,20 @@
 # Install Node modules in the node-packages.txt package list.
 
 set -u
-set -C
 
-# install required node.js modules
+node=$(which node)
+if [ -z "${node}" -o ! -x "${node}" ]; then
+    echo "error: node is not installed, skipping node module installation"
+    exit 1
+fi
+
 npm=$(which npm)
 if [ -z "${npm}" -o ! -x "${npm}" ]; then
-    echo "info: npm is not installed, skipping node module installation"
-else
-    node_modules=$(cat node-packages.txt)
-    for m in ${node_modules} ; do
-        ${npm} install --global --prefix=~/.node_modules "${m}"
-    done
+    echo "error: npm is not installed, skipping node module installation"
+    exit 1
 fi
+
+node_modules=$(cat node-packages.txt)
+for m in ${node_modules} ; do
+    ${npm} install --global --prefix=~/.node_modules "${m}"
+done
diff --git a/install_python_packages b/install_python_packages
--- a/install_python_packages
+++ b/install_python_packages
@@ -3,30 +3,28 @@
 # Install Python modules in the python-packages.txt requirements file.
 
 set -u
-set -C
 
-# install useful python modules if python is installed
 python=$(which python)
-if [ ! -z "${python}" -a -x "${python}" ]; then
-    # install pip if it is not installed
-    pip=$(which pip)
-    if [ -z "${pip}" -o ! -x "${pip}" ]; then
-        pip="$(python -c 'import site ; print site.USER_BASE')/bin/pip"
-        if [ -z "${pip}" -o ! -x "${pip}" ]; then
-            wget https://bootstrap.pypa.io/get-pip.py
-            if [ -e get-pip.py ]; then
-                ${python} get-pip.py --user
-                rm get-pip.py
-            fi
-        fi
-    fi
+if [ -z "${python}" -o ! -x "${python}" ]; then
+    echo "error: Python not installed, not installing Python packages."
+    exit 1
+fi
 
-    # check if pip is available
-    if [ -z "${pip}" -o ! -x "${pip}" ]; then
-        echo "'pip' is not available"
+pip="$(python -c 'import site ; print site.USER_BASE')/bin/pip"
+if [ -z "${pip}" -o ! -x "${pip}" ]; then
+    wget https://bootstrap.pypa.io/get-pip.py
+    if [ ! -e get-pip.py ]; then
+        echo "warning: pip failed to install, not installing Python packages."
         exit 1
     fi
 
-    # install requirements
-    ${pip} install --user --upgrade -r python-packages.txt
+    ${python} get-pip.py --user
+    rm get-pip.py
 fi
+
+if [ -z "${pip}" -o ! -x "${pip}" ]; then
+    echo "error: pip not installing, not installing Python packages."
+    exit 1
+fi
+
+${pip} install --user --upgrade -r python-packages.txt
diff --git a/install_ruby_packages b/install_ruby_packages
--- a/install_ruby_packages
+++ b/install_ruby_packages
@@ -3,23 +3,25 @@
 # Install Ruby modules in the ruby-packages.gemfile Gemfile.
 
 set -u
-set -C
 
-# install useful ruby modules if ruby is installed
 ruby=$(which ruby)
-if [ ! -z "${ruby}" -a -x "${ruby}" ]; then
-    # install required Ruby modules
-    gem=$(which gem)
-    if [ -z "${gem}" -o ! -x "${gem}" ]; then
-        echo "info: gem is not available, skipping Ruby module installation"
-    else
-        ${gem} install --user-install bundler
-
-        bundle="$(ruby -rubygems -e 'puts Gem.user_dir')/bin/bundle"
-        if [ -z "${bundle}" -o ! -x "${bundle}" ]; then
-            echo "info: failed to install bundler, skipping Ruby module installation"
-        else
-            ${bundle} install --path ~/.gem --gemfile=ruby-packages.gemfile
-        fi
-    fi
+if [ -z "${ruby}" -o ! -x "${ruby}" ]; then
+    echo "error: Ruby not installed, not installing Ruby packages."
+    exit 1
 fi
+
+gem=$(which gem)
+if [ -z "${gem}" -o ! -x "${gem}" ]; then
+    echo "error: gem is not available, skipping Ruby module installation"
+    exit 1
+fi
+
+${gem} install --user-install bundler
+
+bundle="$(ruby -rubygems -e 'puts Gem.user_dir')/bin/bundle"
+if [ -z "${bundle}" -o ! -x "${bundle}" ]; then
+    echo "error: failed to install bundler, skipping Ruby module installation"
+    exit 1
+fi
+
+${bundle} install --path ~/.gem --gemfile=ruby-packages.gemfile
