install: Use single-quoted format strings in printf.

diff --git a/install_boost b/install_boost
--- a/install_boost
+++ b/install_boost
@@ -7,28 +7,28 @@ set -u
 set -e
 
 if [ $# -ne 1 ]; then
-    printf "usage: %s <version>\n" "$(basename "$0")" 1>&2
+    printf 'usage: %s <version>\n' "$(basename "$0")" 1>&2
     exit 1
 fi
 
 readonly version="$1"
-readonly version_name="$(printf "%s" "${version}" | sed 's/\./_/g')"
+readonly version_name="$(printf '%s' "${version}" | sed 's/\./_/g')"
 readonly root="${HOME}"/opt/local/src/boost
 readonly directory=boost_"${version_name}"
 readonly filename="${directory}".tar.gz
 
 if [ ! -d "${root}" ]; then
-    printf "error: %s does not exist.\n" "${root}" 1>&2
+    printf 'error: %s does not exist.\n' "${root}" 1>&2
     exit 1
 fi
 
 if [ -d "${root}"/"${directory}" ]; then
-    printf "error: %s already exists.\n" "${root}/${directory}" 1>&2
+    printf 'error: %s already exists.\n' "${root}/${directory}" 1>&2
     exit 1
 fi
 
 if [ -e "${root}"/"${filename}" ]; then
-    printf "error: %s already exists.\n" "${root}/${filename} " 1>&2
+    printf 'error: %s already exists.\n' "${root}/${filename} " 1>&2
     exit 1
 fi
 
@@ -37,14 +37,14 @@ readonly url=https://archives.boost.io/release/"${version}"/source/"${filename}"
 curl --no-clobber --location --remote-name --output-dir "${root}" "${url}"
 
 if [ ! -e "${root}"/"${filename}" ]; then
-    printf "error: %s does not exist.\n" "${root}/${filename}" 1>&2
+    printf 'error: %s does not exist.\n' "${root}/${filename}" 1>&2
     exit 1
 fi
 
 tar -x -z -f "${root}"/"${filename}" -C "${root}"
 
 if [ ! -d "${root}"/"${directory}" ]; then
-    printf "error: %s does not exist.\n" "${root}/${directory} " 1>&2
+    printf 'error: %s does not exist.\n' "${root}/${directory} " 1>&2
     exit 1
 fi
 
diff --git a/install_emacs_macos b/install_emacs_macos
--- a/install_emacs_macos
+++ b/install_emacs_macos
@@ -4,7 +4,7 @@ set -e
 set -u
 
 if [ "$#" -gt 1 ]; then
-    printf "usage: %s [branch]\n" "$0" 1>&2
+    printf 'usage: %s [branch]\n' "$0" 1>&2
     exit 1
 fi
 
@@ -12,7 +12,7 @@ readonly branch="${1:-master}"
 readonly rootdir="${HOME}"/opt/local/src/emacs
 
 if [ ! -e "${rootdir}" ]; then
-    printf "error: %s does not exist.\n" "${rootdir}" 1>&2
+    printf 'error: %s does not exist.\n' "${rootdir}" 1>&2
     exit 1
 fi
 
@@ -24,7 +24,7 @@ readonly packages
 
 for package in ${packages} ; do
     if ! (brew list --formula | grep "${package}" > /dev/null) ; then
-        printf "error: %s is not installed.\n" "${package}" 1>&2
+        printf 'error: %s is not installed.\n' "${package}" 1>&2
         exit 1
     fi
 done
diff --git a/install_system_packages_debian b/install_system_packages_debian
--- a/install_system_packages_debian
+++ b/install_system_packages_debian
@@ -19,7 +19,7 @@ pm_cleanup=
 
 # check if apt is installed
 if [ -z "$(command -v apt 2> /dev/null)" ]; then
-    printf "warning: apt not found\n" 1>&2
+    printf 'warning: apt not found\n' 1>&2
 else
     pm="apt"
     pm_check="true"
@@ -32,14 +32,14 @@ fi
 
 # check if package manager is installed
 if [ -z "${pm}" ]; then
-    printf "error: Package manager not found.\n" 1>&2
+    printf 'error: Package manager not found.\n' 1>&2
     exit 1
 fi
 
 # update and check packages
 ${pm_update}
 if ! ${pm_check} ; then
-    printf "warning: Package manager check failed, continue anyway (y/n)?: "
+    printf 'warning: Package manager check failed, continue anyway (y/n)?: '
     read -r yn
     if [ "${yn}" != "y" ]; then
 	exit 1
diff --git a/install_system_packages_fedora b/install_system_packages_fedora
--- a/install_system_packages_fedora
+++ b/install_system_packages_fedora
@@ -35,7 +35,7 @@ pm_cleanup=
 
 # check if dnf is installed
 if [ -z "$(command -v dnf 2> /dev/null)" ]; then
-    printf "warning: dnf not found.\n" 1>&2
+    printf 'warning: dnf not found.\n' 1>&2
 else
     pm="dnf"
     pm_check="true"
@@ -54,7 +54,7 @@ fi
 # check if yum is installed, if package manager is not
 if [ -z "${pm}" ]; then
     if [ -z "$(command -v yum 2> /dev/null)" ]; then
-        printf "warning: yum not found.\n" 1>&2
+        printf 'warning: yum not found.\n' 1>&2
     else
         pm="yum"
         pm_check="true"
@@ -68,14 +68,14 @@ fi
 
 # check if package manager is installed
 if [ -z "${pm}" ]; then
-    printf "error: Package manager not found.\n" 1>&2
+    printf 'error: Package manager not found.\n' 1>&2
     exit 1
 fi
 
 # update and check packages
 ${pm_update}
 if ! ${pm_check} ; then
-    printf "warning: Package manager check failed, continue anyway (y/n)?: "
+    printf 'warning: Package manager check failed, continue anyway (y/n)?: '
     read -r yn
     if [ "${yn}" != "y" ]; then
 	exit 1
diff --git a/install_system_packages_macos b/install_system_packages_macos
--- a/install_system_packages_macos
+++ b/install_system_packages_macos
@@ -19,7 +19,7 @@ pm_autoremove=
 
 # check if Homebrew is installed
 if [ -z "$(command -v brew 2> /dev/null)" ]; then
-    printf "warning: Homewbrew (brew) not found.\n" 1>&2
+    printf 'warning: Homewbrew (brew) not found.\n' 1>&2
 else
     pm="brew"
     pm_check="${pm} doctor"
@@ -41,7 +41,7 @@ ${pm_install}
 # update and check packages
 ${pm_update}
 if ! ${pm_check} ; then
-    printf "warning: Package manager check failed, continue anyway (y/n)?: "
+    printf 'warning: Package manager check failed, continue anyway (y/n)?: '
     read -r yn
     if [ "${yn}" != "y" ]; then
 	exit 1
