[node] Account for Linux naming of node program.
Some Linux distributions use nodejs instead of node.

diff --git a/install_node_packages b/install_node_packages
--- a/install_node_packages
+++ b/install_node_packages
@@ -6,8 +6,11 @@ set -u
 
 node=$(which node 2> /dev/null)
 if [ -z "${node}" ] || [ ! -x "${node}" ]; then
-    echo "error: node is not installed, skipping node module installation"
-    exit 1
+    node=$(which nodejs 2> /dev/null)
+    if [ -z "${node}" ] || [ ! -x "${node}" ]; then
+        echo "error: node is not installed, skipping node module installation"
+        exit 1
+    fi
 fi
 
 npm=$(which npm 2> /dev/null)
