[system] Unified package manager check.
All systems now check the package manager and exit on failure if
requested.

diff --git a/install_system_packages_debian b/install_system_packages_debian
--- a/install_system_packages_debian
+++ b/install_system_packages_debian
@@ -42,6 +42,14 @@ fi
 
 # update and check packages
 ${pm_update}
+if ! ${pm_check} ; then
+    echo "warning: Package manager check failed, continue anyway (y/n)?: \c"
+    read -r yn
+    if [ "${yn}" != "y" ]; then
+	exit 1
+    fi
+fi
+${pm_update}
 
 # upgrade existing packages
 ${pm_upgrade}
